version: "3.9"
services:
  frontend:
    build: ./app/frontend
    container_name: nobuzz_frontend
    volumes:
      - ./app/frontend:/frontend
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
    ports:
      - 5173:5173
  backend:
    build: ./app/backend
    container_name: nobuzz_backend
    volumes:
      - ./app/backend:/backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
    ports:
      - 3001:3001
  db:
    image: postgres
    container_name: nobuzz_db
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "3002:5432"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "nobuzz_db"]
      interval: 3s
      timeout: 20s
      retries: 5
